// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_actions_id_ from "./routes/admin/actions/[id].tsx";
import * as $admin_actions_edit_id_ from "./routes/admin/actions/edit/[id].tsx";
import * as $admin_actions_index from "./routes/admin/actions/index.tsx";
import * as $admin_actions_new from "./routes/admin/actions/new.tsx";
import * as $admin_cutflower_treatments_id_ from "./routes/admin/cutflower-treatments/[id].tsx";
import * as $admin_cutflower_treatments_edit_id_ from "./routes/admin/cutflower-treatments/edit/[id].tsx";
import * as $admin_cutflower_treatments_index from "./routes/admin/cutflower-treatments/index.tsx";
import * as $admin_cutflower_treatments_new from "./routes/admin/cutflower-treatments/new.tsx";
import * as $admin_cutflowers_id_ from "./routes/admin/cutflowers/[id].tsx";
import * as $admin_cutflowers_edit_id_ from "./routes/admin/cutflowers/edit/[id].tsx";
import * as $admin_cutflowers_index from "./routes/admin/cutflowers/index.tsx";
import * as $admin_cutflowers_new from "./routes/admin/cutflowers/new.tsx";
import * as $admin_garden_beds_index from "./routes/admin/garden/beds/index.tsx";
import * as $admin_garden_beds_new from "./routes/admin/garden/beds/new.tsx";
import * as $admin_garden_crop_rotations_id_ from "./routes/admin/garden/crop-rotations/[id].tsx";
import * as $admin_garden_crop_rotations_edit_id_ from "./routes/admin/garden/crop-rotations/edit/[id].tsx";
import * as $admin_garden_crop_rotations_index from "./routes/admin/garden/crop-rotations/index.tsx";
import * as $admin_garden_crop_rotations_new from "./routes/admin/garden/crop-rotations/new.tsx";
import * as $admin_garden_plantings_id_ from "./routes/admin/garden/plantings/[id].tsx";
import * as $admin_garden_plantings_edit_id_ from "./routes/admin/garden/plantings/edit/[id].tsx";
import * as $admin_garden_plantings_index from "./routes/admin/garden/plantings/index.tsx";
import * as $admin_garden_plantings_new from "./routes/admin/garden/plantings/new.tsx";
import * as $admin_garden_plots_id_ from "./routes/admin/garden/plots/[id].tsx";
import * as $admin_garden_plots_edit_id_ from "./routes/admin/garden/plots/edit/[id].tsx";
import * as $admin_garden_plots_index from "./routes/admin/garden/plots/index.tsx";
import * as $admin_garden_plots_new from "./routes/admin/garden/plots/new.tsx";
import * as $admin_growing_index from "./routes/admin/growing/index.tsx";
import * as $admin_herbal_actions_new from "./routes/admin/herbal-actions/new.tsx";
import * as $admin_medicinal_id_ from "./routes/admin/medicinal/[id].tsx";
import * as $admin_medicinal_edit_id_ from "./routes/admin/medicinal/edit/[id].tsx";
import * as $admin_medicinal_index from "./routes/admin/medicinal/index.tsx";
import * as $admin_medicinal_new from "./routes/admin/medicinal/new.tsx";
import * as $admin_parts_id_ from "./routes/admin/parts/[id].tsx";
import * as $admin_parts_edit_id_ from "./routes/admin/parts/edit/[id].tsx";
import * as $admin_parts_index from "./routes/admin/parts/index.tsx";
import * as $admin_parts_new from "./routes/admin/parts/new.tsx";
import * as $admin_plants_id_actions_add from "./routes/admin/plants/[id]/actions/add.tsx";
import * as $admin_plants_id_actions_index from "./routes/admin/plants/[id]/actions/index.tsx";
import * as $admin_plants_id_ayurvedic_add from "./routes/admin/plants/[id]/ayurvedic/add.tsx";
import * as $admin_plants_id_ayurvedic_edit from "./routes/admin/plants/[id]/ayurvedic/edit.tsx";
import * as $admin_plants_id_ayurvedic_index from "./routes/admin/plants/[id]/ayurvedic/index.tsx";
import * as $admin_plants_id_culinary_add from "./routes/admin/plants/[id]/culinary/add.tsx";
import * as $admin_plants_id_culinary_edit from "./routes/admin/plants/[id]/culinary/edit.tsx";
import * as $admin_plants_id_culinary_index from "./routes/admin/plants/[id]/culinary/index.tsx";
import * as $admin_plants_id_growing_islands_new from "./routes/admin/plants/[id]/growing/_islands/new.tsx";
import * as $admin_plants_id_growing_index from "./routes/admin/plants/[id]/growing/index.tsx";
import * as $admin_plants_id_medicinal_index from "./routes/admin/plants/[id]/medicinal/index.tsx";
import * as $admin_plants_id_medicinal_new from "./routes/admin/plants/[id]/medicinal/new.tsx";
import * as $admin_plants_id_parts_add from "./routes/admin/plants/[id]/parts/add.tsx";
import * as $admin_plants_id_parts_edit from "./routes/admin/plants/[id]/parts/edit.tsx";
import * as $admin_plants_id_parts_index from "./routes/admin/plants/[id]/parts/index.tsx";
import * as $admin_plants_id_parts_new from "./routes/admin/plants/[id]/parts/new.tsx";
import * as $admin_plants_id_recipes_index from "./routes/admin/plants/[id]/recipes/index.tsx";
import * as $admin_plants_id_seeds_add from "./routes/admin/plants/[id]/seeds/add.tsx";
import * as $admin_plants_id_seeds_edit from "./routes/admin/plants/[id]/seeds/edit.tsx";
import * as $admin_plants_id_seeds_index from "./routes/admin/plants/[id]/seeds/index.tsx";
import * as $admin_plants_id_tcm_add from "./routes/admin/plants/[id]/tcm/add.tsx";
import * as $admin_plants_id_tcm_edit from "./routes/admin/plants/[id]/tcm/edit.tsx";
import * as $admin_plants_id_tcm_index from "./routes/admin/plants/[id]/tcm/index.tsx";
import * as $admin_plants_id_western_medicine_add from "./routes/admin/plants/[id]/western-medicine/add.tsx";
import * as $admin_plants_id_western_medicine_edit from "./routes/admin/plants/[id]/western-medicine/edit.tsx";
import * as $admin_plants_id_western_medicine_index from "./routes/admin/plants/[id]/western-medicine/index.tsx";
import * as $admin_plants_ayurvedic_id_ from "./routes/admin/plants/ayurvedic/[id].tsx";
import * as $admin_plants_ayurvedic_new_id_ from "./routes/admin/plants/ayurvedic/new/[id].tsx";
import * as $admin_plants_culinary_id_ from "./routes/admin/plants/culinary/[id].tsx";
import * as $admin_plants_culinary_edit_id_ from "./routes/admin/plants/culinary/edit/[id].tsx";
import * as $admin_plants_culinary_new_id_ from "./routes/admin/plants/culinary/new/[id].tsx";
import * as $admin_plants_details_id_ from "./routes/admin/plants/details/[id].tsx";
import * as $admin_plants_edit_id_ from "./routes/admin/plants/edit/[id].tsx";
import * as $admin_plants_growing_id_ from "./routes/admin/plants/growing/[id].tsx";
import * as $admin_plants_growing_edit_id_ from "./routes/admin/plants/growing/edit/[id].tsx";
import * as $admin_plants_growing_new_id_ from "./routes/admin/plants/growing/new/[id].tsx";
import * as $admin_plants_index from "./routes/admin/plants/index.tsx";
import * as $admin_plants_medicinal_id_ from "./routes/admin/plants/medicinal/[id].tsx";
import * as $admin_plants_medicinal_edit_id_ from "./routes/admin/plants/medicinal/edit/[id].tsx";
import * as $admin_plants_medicinal_new_id_ from "./routes/admin/plants/medicinal/new/[id].tsx";
import * as $admin_plants_new from "./routes/admin/plants/new.tsx";
import * as $admin_plants_parts_id_ from "./routes/admin/plants/parts/[id].tsx";
import * as $admin_plants_parts_edit_plantId_partId_ from "./routes/admin/plants/parts/edit/[plantId]/[partId].tsx";
import * as $admin_plants_parts_new_id_ from "./routes/admin/plants/parts/new/[id].tsx";
import * as $admin_plants_recipes_id_ from "./routes/admin/plants/recipes/[id].tsx";
import * as $admin_plants_seeds_id_ from "./routes/admin/plants/seeds/[id].tsx";
import * as $admin_plants_seeds_edit_id_ from "./routes/admin/plants/seeds/edit/[id].tsx";
import * as $admin_plants_seeds_new_id_ from "./routes/admin/plants/seeds/new/[id].tsx";
import * as $admin_plants_tcm_id_ from "./routes/admin/plants/tcm/[id].tsx";
import * as $admin_plants_western_medicine_id_ from "./routes/admin/plants/western-medicine/[id].tsx";
import * as $admin_plants_western_medicine_edit_id_ from "./routes/admin/plants/western-medicine/edit/[id].tsx";
import * as $admin_plants_western_medicine_new_id_ from "./routes/admin/plants/western-medicine/new/[id].tsx";
import * as $api_garden_beds_id_ from "./routes/api/garden/beds/[id].ts";
import * as $api_garden_beds_by_plot_plotId_ from "./routes/api/garden/beds/by-plot/[plotId].ts";
import * as $api_garden_beds_index from "./routes/api/garden/beds/index.ts";
import * as $api_garden_crop_rotations_id_ from "./routes/api/garden/crop-rotations/[id].ts";
import * as $api_garden_crop_rotations_index from "./routes/api/garden/crop-rotations/index.ts";
import * as $api_garden_plantings_id_ from "./routes/api/garden/plantings/[id].ts";
import * as $api_garden_plantings_index from "./routes/api/garden/plantings/index.ts";
import * as $api_garden_plots_id_ from "./routes/api/garden/plots/[id].ts";
import * as $api_garden_plots_index from "./routes/api/garden/plots/index.ts";
import * as $api_garden_plots_next_code from "./routes/api/garden/plots/next-code.ts";
import * as $api_growing_records from "./routes/api/growing-records.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_plants_delete_id_ from "./routes/api/plants/delete/[id].ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $plants_id_ from "./routes/plants/[id].tsx";
import * as $plants_index from "./routes/plants/index.tsx";
import * as $AyurvedicPropertiesForm from "./islands/AyurvedicPropertiesForm.tsx";
import * as $BaseFormIsland from "./islands/BaseFormIsland.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CropRotationForm from "./islands/CropRotationForm.tsx";
import * as $CulinaryUsesForm from "./islands/CulinaryUsesForm.tsx";
import * as $DeletePlantButton from "./islands/DeletePlantButton.tsx";
import * as $DeletePlotButton from "./islands/DeletePlotButton.tsx";
import * as $GardenBedForm from "./islands/GardenBedForm.tsx";
import * as $GrowingGuideForm from "./islands/GrowingGuideForm.tsx";
import * as $HerbalPreparationForm from "./islands/HerbalPreparationForm.tsx";
import * as $PlantForm from "./islands/PlantForm.tsx";
import * as $PlantFormSidebar from "./islands/PlantFormSidebar.tsx";
import * as $PlantingForm from "./islands/PlantingForm.tsx";
import * as $PlotForm from "./islands/PlotForm.tsx";
import * as $SeedSavingForm from "./islands/SeedSavingForm.tsx";
import * as $TreatmentForm from "./islands/TreatmentForm.tsx";
import * as $WesternMedicineForm from "./islands/WesternMedicineForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/actions/[id].tsx": $admin_actions_id_,
    "./routes/admin/actions/edit/[id].tsx": $admin_actions_edit_id_,
    "./routes/admin/actions/index.tsx": $admin_actions_index,
    "./routes/admin/actions/new.tsx": $admin_actions_new,
    "./routes/admin/cutflower-treatments/[id].tsx":
      $admin_cutflower_treatments_id_,
    "./routes/admin/cutflower-treatments/edit/[id].tsx":
      $admin_cutflower_treatments_edit_id_,
    "./routes/admin/cutflower-treatments/index.tsx":
      $admin_cutflower_treatments_index,
    "./routes/admin/cutflower-treatments/new.tsx":
      $admin_cutflower_treatments_new,
    "./routes/admin/cutflowers/[id].tsx": $admin_cutflowers_id_,
    "./routes/admin/cutflowers/edit/[id].tsx": $admin_cutflowers_edit_id_,
    "./routes/admin/cutflowers/index.tsx": $admin_cutflowers_index,
    "./routes/admin/cutflowers/new.tsx": $admin_cutflowers_new,
    "./routes/admin/garden/beds/index.tsx": $admin_garden_beds_index,
    "./routes/admin/garden/beds/new.tsx": $admin_garden_beds_new,
    "./routes/admin/garden/crop-rotations/[id].tsx":
      $admin_garden_crop_rotations_id_,
    "./routes/admin/garden/crop-rotations/edit/[id].tsx":
      $admin_garden_crop_rotations_edit_id_,
    "./routes/admin/garden/crop-rotations/index.tsx":
      $admin_garden_crop_rotations_index,
    "./routes/admin/garden/crop-rotations/new.tsx":
      $admin_garden_crop_rotations_new,
    "./routes/admin/garden/plantings/[id].tsx": $admin_garden_plantings_id_,
    "./routes/admin/garden/plantings/edit/[id].tsx":
      $admin_garden_plantings_edit_id_,
    "./routes/admin/garden/plantings/index.tsx": $admin_garden_plantings_index,
    "./routes/admin/garden/plantings/new.tsx": $admin_garden_plantings_new,
    "./routes/admin/garden/plots/[id].tsx": $admin_garden_plots_id_,
    "./routes/admin/garden/plots/edit/[id].tsx": $admin_garden_plots_edit_id_,
    "./routes/admin/garden/plots/index.tsx": $admin_garden_plots_index,
    "./routes/admin/garden/plots/new.tsx": $admin_garden_plots_new,
    "./routes/admin/growing/index.tsx": $admin_growing_index,
    "./routes/admin/herbal-actions/new.tsx": $admin_herbal_actions_new,
    "./routes/admin/medicinal/[id].tsx": $admin_medicinal_id_,
    "./routes/admin/medicinal/edit/[id].tsx": $admin_medicinal_edit_id_,
    "./routes/admin/medicinal/index.tsx": $admin_medicinal_index,
    "./routes/admin/medicinal/new.tsx": $admin_medicinal_new,
    "./routes/admin/parts/[id].tsx": $admin_parts_id_,
    "./routes/admin/parts/edit/[id].tsx": $admin_parts_edit_id_,
    "./routes/admin/parts/index.tsx": $admin_parts_index,
    "./routes/admin/parts/new.tsx": $admin_parts_new,
    "./routes/admin/plants/[id]/actions/add.tsx": $admin_plants_id_actions_add,
    "./routes/admin/plants/[id]/actions/index.tsx":
      $admin_plants_id_actions_index,
    "./routes/admin/plants/[id]/ayurvedic/add.tsx":
      $admin_plants_id_ayurvedic_add,
    "./routes/admin/plants/[id]/ayurvedic/edit.tsx":
      $admin_plants_id_ayurvedic_edit,
    "./routes/admin/plants/[id]/ayurvedic/index.tsx":
      $admin_plants_id_ayurvedic_index,
    "./routes/admin/plants/[id]/culinary/add.tsx":
      $admin_plants_id_culinary_add,
    "./routes/admin/plants/[id]/culinary/edit.tsx":
      $admin_plants_id_culinary_edit,
    "./routes/admin/plants/[id]/culinary/index.tsx":
      $admin_plants_id_culinary_index,
    "./routes/admin/plants/[id]/growing/_islands/new.tsx":
      $admin_plants_id_growing_islands_new,
    "./routes/admin/plants/[id]/growing/index.tsx":
      $admin_plants_id_growing_index,
    "./routes/admin/plants/[id]/medicinal/index.tsx":
      $admin_plants_id_medicinal_index,
    "./routes/admin/plants/[id]/medicinal/new.tsx":
      $admin_plants_id_medicinal_new,
    "./routes/admin/plants/[id]/parts/add.tsx": $admin_plants_id_parts_add,
    "./routes/admin/plants/[id]/parts/edit.tsx": $admin_plants_id_parts_edit,
    "./routes/admin/plants/[id]/parts/index.tsx": $admin_plants_id_parts_index,
    "./routes/admin/plants/[id]/parts/new.tsx": $admin_plants_id_parts_new,
    "./routes/admin/plants/[id]/recipes/index.tsx":
      $admin_plants_id_recipes_index,
    "./routes/admin/plants/[id]/seeds/add.tsx": $admin_plants_id_seeds_add,
    "./routes/admin/plants/[id]/seeds/edit.tsx": $admin_plants_id_seeds_edit,
    "./routes/admin/plants/[id]/seeds/index.tsx": $admin_plants_id_seeds_index,
    "./routes/admin/plants/[id]/tcm/add.tsx": $admin_plants_id_tcm_add,
    "./routes/admin/plants/[id]/tcm/edit.tsx": $admin_plants_id_tcm_edit,
    "./routes/admin/plants/[id]/tcm/index.tsx": $admin_plants_id_tcm_index,
    "./routes/admin/plants/[id]/western-medicine/add.tsx":
      $admin_plants_id_western_medicine_add,
    "./routes/admin/plants/[id]/western-medicine/edit.tsx":
      $admin_plants_id_western_medicine_edit,
    "./routes/admin/plants/[id]/western-medicine/index.tsx":
      $admin_plants_id_western_medicine_index,
    "./routes/admin/plants/ayurvedic/[id].tsx": $admin_plants_ayurvedic_id_,
    "./routes/admin/plants/ayurvedic/new/[id].tsx":
      $admin_plants_ayurvedic_new_id_,
    "./routes/admin/plants/culinary/[id].tsx": $admin_plants_culinary_id_,
    "./routes/admin/plants/culinary/edit/[id].tsx":
      $admin_plants_culinary_edit_id_,
    "./routes/admin/plants/culinary/new/[id].tsx":
      $admin_plants_culinary_new_id_,
    "./routes/admin/plants/details/[id].tsx": $admin_plants_details_id_,
    "./routes/admin/plants/edit/[id].tsx": $admin_plants_edit_id_,
    "./routes/admin/plants/growing/[id].tsx": $admin_plants_growing_id_,
    "./routes/admin/plants/growing/edit/[id].tsx":
      $admin_plants_growing_edit_id_,
    "./routes/admin/plants/growing/new/[id].tsx": $admin_plants_growing_new_id_,
    "./routes/admin/plants/index.tsx": $admin_plants_index,
    "./routes/admin/plants/medicinal/[id].tsx": $admin_plants_medicinal_id_,
    "./routes/admin/plants/medicinal/edit/[id].tsx":
      $admin_plants_medicinal_edit_id_,
    "./routes/admin/plants/medicinal/new/[id].tsx":
      $admin_plants_medicinal_new_id_,
    "./routes/admin/plants/new.tsx": $admin_plants_new,
    "./routes/admin/plants/parts/[id].tsx": $admin_plants_parts_id_,
    "./routes/admin/plants/parts/edit/[plantId]/[partId].tsx":
      $admin_plants_parts_edit_plantId_partId_,
    "./routes/admin/plants/parts/new/[id].tsx": $admin_plants_parts_new_id_,
    "./routes/admin/plants/recipes/[id].tsx": $admin_plants_recipes_id_,
    "./routes/admin/plants/seeds/[id].tsx": $admin_plants_seeds_id_,
    "./routes/admin/plants/seeds/edit/[id].tsx": $admin_plants_seeds_edit_id_,
    "./routes/admin/plants/seeds/new/[id].tsx": $admin_plants_seeds_new_id_,
    "./routes/admin/plants/tcm/[id].tsx": $admin_plants_tcm_id_,
    "./routes/admin/plants/western-medicine/[id].tsx":
      $admin_plants_western_medicine_id_,
    "./routes/admin/plants/western-medicine/edit/[id].tsx":
      $admin_plants_western_medicine_edit_id_,
    "./routes/admin/plants/western-medicine/new/[id].tsx":
      $admin_plants_western_medicine_new_id_,
    "./routes/api/garden/beds/[id].ts": $api_garden_beds_id_,
    "./routes/api/garden/beds/by-plot/[plotId].ts":
      $api_garden_beds_by_plot_plotId_,
    "./routes/api/garden/beds/index.ts": $api_garden_beds_index,
    "./routes/api/garden/crop-rotations/[id].ts":
      $api_garden_crop_rotations_id_,
    "./routes/api/garden/crop-rotations/index.ts":
      $api_garden_crop_rotations_index,
    "./routes/api/garden/plantings/[id].ts": $api_garden_plantings_id_,
    "./routes/api/garden/plantings/index.ts": $api_garden_plantings_index,
    "./routes/api/garden/plots/[id].ts": $api_garden_plots_id_,
    "./routes/api/garden/plots/index.ts": $api_garden_plots_index,
    "./routes/api/garden/plots/next-code.ts": $api_garden_plots_next_code,
    "./routes/api/growing-records.ts": $api_growing_records,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/plants/delete/[id].ts": $api_plants_delete_id_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/plants/[id].tsx": $plants_id_,
    "./routes/plants/index.tsx": $plants_index,
  },
  islands: {
    "./islands/AyurvedicPropertiesForm.tsx": $AyurvedicPropertiesForm,
    "./islands/BaseFormIsland.tsx": $BaseFormIsland,
    "./islands/Counter.tsx": $Counter,
    "./islands/CropRotationForm.tsx": $CropRotationForm,
    "./islands/CulinaryUsesForm.tsx": $CulinaryUsesForm,
    "./islands/DeletePlantButton.tsx": $DeletePlantButton,
    "./islands/DeletePlotButton.tsx": $DeletePlotButton,
    "./islands/GardenBedForm.tsx": $GardenBedForm,
    "./islands/GrowingGuideForm.tsx": $GrowingGuideForm,
    "./islands/HerbalPreparationForm.tsx": $HerbalPreparationForm,
    "./islands/PlantForm.tsx": $PlantForm,
    "./islands/PlantFormSidebar.tsx": $PlantFormSidebar,
    "./islands/PlantingForm.tsx": $PlantingForm,
    "./islands/PlotForm.tsx": $PlotForm,
    "./islands/SeedSavingForm.tsx": $SeedSavingForm,
    "./islands/TreatmentForm.tsx": $TreatmentForm,
    "./islands/WesternMedicineForm.tsx": $WesternMedicineForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
